### ISSUE TITLE
Баг в логике отправки приглашений при определении зафейлившихся 

### ISSUE THREAD

**Issue by ronimizy** [kysect/GithubUtils#29]
В начале цикла, если эксепшен не нул, инвайт помечается как зафейлившийся, таким образом, все юзеры после первого зафейлившегося будут в этом списке и не будут приглашены 

https://github.com/kysect/GithubUtils/blob/282326b7dbdb7c01de798133501452da42bff8de/Kysect.GithubUtils/Inviting/OrganizationInviteSender.cs#L68-L92

**Comment by FrediKats** [comment]
Это, вроде как, бай дизайн, чтобы при первой ошибке квоты не идти дальше и не отправлять ещё миллион инвайтов и не ловить бан от гитхаба. Способов определить, что ты лимит в 50 запросов перешёл нет :с

**Comment by ronimizy** [comment]
Ну, во первых, для этого можно ловить Forbidden эксепшн, во вторых хотелось бы чтобы они были как-то отдельно от failed, ну и наконец, хотелось бы иметь на каждого failed эксепшн с которым он упал, а не первый…
